/**
 * Comment formatter for Bitbucket code review comments.
 * Handles AI tagging, severity formatting, code suggestions, and update markers.
 * Tags are configurable via the BITBUCKET_AI_TAG environment variable.
 */

export type Severity = "suggestion" | "warning" | "bug" | "note" | "security";

const SEVERITY_EMOJI: Record<Severity, string> = {
  suggestion: "💡",
  warning: "⚠️",
  bug: "🐛",
  note: "📝",
  security: "🔒",
};

const SEVERITY_LABEL: Record<Severity, string> = {
  suggestion: "Suggestion",
  warning: "Warning",
  bug: "Bug",
  note: "Note",
  security: "Security",
};

/**
 * Get the configurable AI review tag from environment or use default.
 * Set BITBUCKET_AI_TAG="" to disable tagging entirely.
 */
export function getAITag(): string {
  const envTag = process.env.BITBUCKET_AI_TAG;
  if (envTag !== undefined) return envTag; // empty string = disabled
  return "🤖 AI Review";
}

/**
 * Check whether the AI tag is enabled (non-empty).
 */
export function isTagEnabled(): boolean {
  return getAITag().length > 0;
}

/**
 * Get the configurable AI update marker.
 */
export function getUpdateMarker(): string {
  return `✏️ Updated by AI`;
}

/**
 * Check if a comment was generated by AI (contains the AI tag).
 */
export function isAIComment(commentRaw: string): boolean {
  const tag = getAITag();
  if (!tag) return false; // tagging disabled — no comments are "AI"
  return commentRaw.includes(tag) || commentRaw.includes("[AI Review]");
}

/**
 * Build the tag prefix string. Returns empty string if tag is disabled.
 */
function tagPrefix(suffix?: string): string {
  const tag = getAITag();
  if (!tag) return suffix ? `${suffix}\n\n` : "";
  return suffix ? `**[${tag}]** ${suffix}\n\n` : `**[${tag}]**\n\n`;
}

/**
 * Format a general review comment with optional AI tag.
 */
export function formatGeneralComment(comment: string): string {
  return `${tagPrefix()}${comment}`;
}

/**
 * Format an inline comment with optional AI tag and optional severity.
 */
export function formatInlineComment(
  comment: string,
  severity?: Severity
): string {
  if (severity) {
    const emoji = SEVERITY_EMOJI[severity];
    const label = SEVERITY_LABEL[severity];
    return `${tagPrefix(`${emoji} **${label}**`)}${comment}`;
  }
  return `${tagPrefix()}${comment}`;
}

/**
 * Format a code suggestion using Bitbucket's /suggest syntax.
 * This renders as an "Apply suggestion" button in Bitbucket UI.
 */
export function formatCodeSuggestion(
  suggestedCode: string,
  explanation?: string
): string {
  const parts: string[] = [tagPrefix(`💡 **Suggestion**`).trimEnd()];

  if (explanation) {
    parts.push("", explanation);
  }

  parts.push("", "```suggestion", suggestedCode, "```");

  return parts.join("\n");
}

/**
 * Format an updated comment — appends the update marker.
 */
export function formatUpdatedComment(
  existingContent: string,
  newContent: string
): string {
  const marker = getUpdateMarker();
  return `${existingContent}\n\n---\n\n**[${marker}]**\n\n${newContent}`;
}

/**
 * Format a reply comment with AI tag.
 */
export function formatReply(comment: string): string {
  return `${tagPrefix()}${comment}`;
}

/**
 * Format a file-level comment.
 */
export function formatFileLevelComment(
  comment: string,
  severity?: Severity
): string {
  return formatInlineComment(comment, severity);
}

/**
 * Map the skill output severity to our severity type.
 */
export function mapSkillSeverity(
  skillSeverity: string
): Severity | undefined {
  const normalized = skillSeverity.toUpperCase();
  switch (normalized) {
    case "CRITICAL":
    case "HIGH":
      return "bug";
    case "MEDIUM":
      return "warning";
    case "LOW":
      return "suggestion";
    default:
      return "note";
  }
}
